module.exports = [
    { label: 'array', type: 'System Class' },
    { label: 'simple-array', type: 'Type' },
    { label: 'vector', type: 'System Class' },
    { label: 'simple-vector', type: 'Type' },
    { label: 'bit-vector', type: 'System Class' },
    { label: 'simple-bit-vector', type: 'Type' },
    { label: 'make-array', type: 'Function' },
    { label: 'adjust-array', type: 'Function' },
    { label: 'adjustable-array-p', type: 'Function' },
    { label: 'aref', type: 'Accessor' },
    { label: 'array-dimension', type: 'Function' },
    { label: 'array-dimensions', type: 'Function' },
    { label: 'array-element-type', type: 'Function' },
    { label: 'array-has-fill-pointer-p', type: 'Function' },
    { label: 'array-displacement', type: 'Function' },
    { label: 'array-in-bounds-p', type: 'Function' },
    { label: 'array-rank', type: 'Function' },
    { label: 'array-row-major-index', type: 'Function' },
    { label: 'array-total-size', type: 'Function' },
    { label: 'arrayp', type: 'Function' },
    { label: 'fill-pointer', type: 'Accessor' },
    { label: 'row-major-aref', type: 'Accessor' },
    { label: 'upgraded-array-element-type', type: 'Function' },
    { label: 'array-dimension-limit', type: 'Constant Variable' },
    { label: 'array-rank-limit', type: 'Constant Variable' },
    { label: 'array-total-size-limit', type: 'Constant Variable' },
    { label: 'simple-vector-p', type: 'Function' },
    { label: 'svref', type: 'Accessor' },
    { label: 'vector', type: 'Function' },
    { label: 'vector-pop', type: 'Function' },
    { label: 'vector-push', type: 'Function' },
    { label: 'vector-push-extend', type: 'Function' },
    { label: 'vectorp', type: 'Function' },
    { label: 'bit', type: 'Accessor' },
    { label: 'sbit', type: 'Function' },
    { label: 'bit-and', type: 'Function' },
    { label: 'bit-andc1', type: 'Function' },
    { label: 'bit-andc2', type: 'Function' },
    { label: 'bit-eqv', type: 'Function' },
    { label: 'bit-ior', type: 'Function' },
    { label: 'bit-nand', type: 'Function' },
    { label: 'bit-nor', type: 'Function' },
    { label: 'bit-not', type: 'Function' },
    { label: 'bit-orc1', type: 'Function' },
    { label: 'bit-orc2', type: 'Function' },
    { label: 'bit-xor', type: 'Function' },
    { label: 'bit-vector-p', type: 'Function' },
    { label: 'simple-bit-vector-p', type: 'Function' },
];
