module.exports = [
    { label: 'condition', type: 'Condition Type' },
    { label: 'warning', type: 'Condition Type' },
    { label: 'style-warning', type: 'Condition Type' },
    { label: 'serious-condition', type: 'Condition Type' },
    { label: 'error', type: 'Condition Type' },
    { label: 'cell-error', type: 'Condition Type' },
    { label: 'cell-error-name', type: 'Function' },
    { label: 'parse-error', type: 'Condition Type' },
    { label: 'storage-condition', type: 'Condition Type' },
    { label: 'assert', type: 'Macro' },
    { label: 'error', type: 'Function' },
    { label: 'cerror', type: 'Function' },
    { label: 'check-type', type: 'Macro' },
    { label: 'simple-error', type: 'Condition Type' },
    { label: 'invalid-method-error', type: 'Function' },
    { label: 'method-combination-error', type: 'Function' },
    { label: 'signal', type: 'Function' },
    { label: 'simple-condition', type: 'Condition Type' },
    { label: 'simple-condition-format-control', type: 'Function' },
    { label: 'simple-condition-format-arguments', type: 'Function' },
    { label: 'warn', type: 'Function' },
    { label: 'simple-warning', type: 'Condition Type' },
    { label: 'invoke-debugger', type: 'Function' },
    { label: 'break', type: 'Function' },
    { label: '*debugger-hook*', type: 'Variable' },
    { label: '*break-on-signals*', type: 'Variable' },
    { label: 'handler-bind', type: 'Macro' },
    { label: 'handler-case', type: 'Macro' },
    { label: 'ignore-errors', type: 'Macro' },
    { label: 'define-condition', type: 'Macro' },
    { label: 'make-condition', type: 'Function' },
    { label: 'restart', type: 'System Class' },
    { label: 'compute-restarts', type: 'Function' },
    { label: 'find-restart', type: 'Function' },
    { label: 'invoke-restart', type: 'Function' },
    { label: 'invoke-restart-interactively', type: 'Function' },
    { label: 'restart-bind', type: 'Macro' },
    { label: 'restart-case', type: 'Macro' },
    { label: 'restart-name', type: 'Function' },
    { label: 'with-condition-restarts', type: 'Macro' },
    { label: 'with-simple-restart', type: 'Macro' },
    { label: 'abort', type: 'Restart' },
    { label: 'continue', type: 'Restart' },
    { label: 'muffle-warning', type: 'Restart' },
    { label: 'store-value', type: 'Restart' },
    { label: 'use-value', type: 'Restart' },
    { label: 'abort', type: 'Function' },
    { label: 'continue', type: 'Function' },
    { label: 'muffle-warning', type: 'Function' },
    { label: 'store-value', type: 'Function' },
    { label: 'use-value', type: 'Function' },
];
