export default [
    { label: 'decode-universal-time', type: 'Function' },
    { label: 'encode-universal-time', type: 'Function' },
    { label: 'get-universal-time', type: 'Function' },
    { label: 'get-decoded-time', type: 'Function' },
    { label: 'sleep', type: 'Function' },
    { label: 'apropos', type: 'Function' },
    { label: 'apropos-list', type: 'Function' },
    { label: 'describe', type: 'Function' },
    { label: 'describe-object', type: 'Standard Generic Function' },
    { label: 'trace', type: 'Macro' },
    { label: 'untrace', type: 'Macro' },
    { label: 'step', type: 'Macro' },
    { label: 'time', type: 'Macro' },
    { label: 'internal-time-units-per-second', type: 'Constant Variable' },
    { label: 'get-internal-real-time', type: 'Function' },
    { label: 'get-internal-run-time', type: 'Function' },
    { label: 'disassemble', type: 'Function' },
    { label: 'room', type: 'Function' },
    { label: 'ed', type: 'Function' },
    { label: 'inspect', type: 'Function' },
    { label: 'dribble', type: 'Function' },
    { label: '++', type: 'Variable' },
    { label: '+++', type: 'Variable' },
    { label: '**', type: 'Variable' },
    { label: '***', type: 'Variable' },
    { label: '//', type: 'Variable' },
    { label: '///', type: 'Variable' },
    { label: 'lisp-implementation-type', type: 'Function' },
    { label: 'lisp-implementation-version', type: 'Function' },
    { label: 'short-site-name', type: 'Function' },
    { label: 'long-site-name', type: 'Function' },
    { label: 'machine-instance', type: 'Function' },
    { label: 'machine-type', type: 'Function' },
    { label: 'machine-version', type: 'Function' },
    { label: 'software-type', type: 'Function' },
    { label: 'software-version', type: 'Function' },
    { label: 'user-homedir-pathname', type: 'Function' },
];
