module.exports = [
    { label: 'pathname', type: 'Function' },
    { label: 'make-pathname', type: 'Function' },
    { label: 'pathnamep', type: 'Function' },
    { label: 'pathname-host', type: 'Function' },
    { label: 'pathname-device', type: 'Function' },
    { label: 'pathname-directory', type: 'Function' },
    { label: 'pathname-name', type: 'Function' },
    { label: 'pathname-type', type: 'Function' },
    { label: 'pathname-version', type: 'Function' },
    { label: 'load-logical-pathname-translations', type: 'Function' },
    { label: 'logical-pathname-translations', type: 'Accessor' },
    { label: 'logical-pathname', type: 'Function' },
    { label: '*default-pathname-defaults*', type: 'Variable' },
    { label: 'namestring', type: 'Function' },
    { label: 'file-namestring', type: 'Function' },
    { label: 'directory-namestring', type: 'Function' },
    { label: 'host-namestring', type: 'Function' },
    { label: 'enough-namestring', type: 'Function' },
    { label: 'parse-namestring', type: 'Function' },
    { label: 'wild-pathname-p', type: 'Function' },
    { label: 'pathname-match-p', type: 'Function' },
    { label: 'translate-logical-pathname', type: 'Function' },
    { label: 'translate-pathname', type: 'Function' },
    { label: 'merge-pathnames', type: 'Function' },
];
