module.exports = [
    { label: 'function-keywords', type: 'Standard Generic Function' },
    { label: 'ensure-generic-function', type: 'Function' },
    { label: 'allocate-instance', type: 'Standard Generic Function' },
    { label: 'reinitialize-instance', type: 'Standard Generic Function' },
    { label: 'shared-initialize', type: 'Standard Generic Function' },
    { label: 'update-instance-for-different-class', type: 'Standard Generic Function' },
    { label: 'update-instance-for-redefined-class', type: 'Standard Generic Function' },
    { label: 'change-class', type: 'Standard Generic Function' },
    { label: 'slot-boundp', type: 'Function' },
    { label: 'slot-exists-p', type: 'Function' },
    { label: 'slot-makunbound', type: 'Function' },
    { label: 'slot-missing', type: 'Standard Generic Function' },
    { label: 'slot-unbound', type: 'Standard Generic Function' },
    { label: 'slot-value', type: 'Function' },
    { label: 'method-qualifiers', type: 'Standard Generic Function' },
    { label: 'no-applicable-method', type: 'Standard Generic Function' },
    { label: 'no-next-method', type: 'Standard Generic Function' },
    { label: 'remove-method', type: 'Standard Generic Function' },
    { label: 'make-instance', type: 'Standard Generic Function' },
    { label: 'make-instances-obsolete', type: 'Standard Generic Function' },
    { label: 'make-load-form', type: 'Standard Generic Function' },
    { label: 'make-load-form-saving-slots', type: 'Function' },
    { label: 'with-accessors', type: 'Macro' },
    { label: 'with-slots', type: 'Macro' },
    { label: 'defclass', type: 'Macro' },
    { label: 'defgeneric', type: 'Macro' },
    { label: 'defmethod', type: 'Macro' },
    { label: 'find-class', type: 'Accessor' },
    { label: 'next-method-p', type: 'Local Function' },
    { label: 'call-method', type: 'Local Macro' },
    { label: 'make-method', type: 'Local Macro' },
    { label: 'call-next-method', type: 'Local Function' },
    { label: 'compute-applicable-methods', type: 'Standard Generic Function' },
    { label: 'define-method-combination', type: 'Macro' },
    { label: 'find-method', type: 'Standard Generic Function' },
    { label: 'add-method', type: 'Standard Generic Function' },
    { label: 'initialize-instance', type: 'Standard Generic Function' },
    { label: 'class-name', type: 'Standard Generic Function' },
    { label: 'class-name)', type: 'Standard Generic Function (SETF' },
    { label: 'class-of', type: 'Function' },
    { label: 'unbound-slot', type: 'Condition Type' },
    { label: 'unbound-slot-instance', type: 'Function' },
];
