export default [
    { label: 'package', type: 'System Class' },
    { label: 'export', type: 'Function' },
    { label: 'find-symbol', type: 'Function' },
    { label: 'find-package', type: 'Function' },
    { label: 'find-all-symbols', type: 'Function' },
    { label: 'import', type: 'Function' },
    { label: 'list-all-packages', type: 'Function' },
    { label: 'rename-package', type: 'Function' },
    { label: 'shadow', type: 'Function' },
    { label: 'shadowing-import', type: 'Function' },
    { label: 'delete-package', type: 'Function' },
    { label: 'make-package', type: 'Function' },
    { label: 'with-package-iterator', type: 'Macro' },
    { label: 'unexport', type: 'Function' },
    { label: 'unintern', type: 'Function' },
    { label: 'in-package', type: 'Macro' },
    { label: 'unuse-package', type: 'Function' },
    { label: 'use-package', type: 'Function' },
    { label: 'defpackage', type: 'Macro' },
    { label: 'do-symbols', type: 'Macro' },
    { label: 'do-external-symbols', type: 'Macro ' },
    { label: 'do-all-symbols', type: 'Macro ' },
    { label: 'intern', type: 'Function' },
    { label: 'package-name', type: 'Function' },
    { label: 'package-nicknames', type: 'Function' },
    { label: 'package-shadowing-symbols', type: 'Function' },
    { label: 'package-use-list', type: 'Function' },
    { label: 'package-used-by-list', type: 'Function' },
    { label: 'packagep', type: 'Function' },
    { label: '*package*', type: 'Variable' },
    { label: 'package-error', type: 'Condition Type' },
    { label: 'package-error-package', type: 'Function' },
];
