module.exports = [
    { label: 'copy-pprint-dispatch', type: 'Function' },
    { label: 'formatter', type: 'Macro' },
    { label: 'pprint-dispatch', type: 'Function' },
    { label: 'pprint-exit-if-list-exhausted', type: 'Local Macro' },
    { label: 'pprint-fill', type: 'Function' },
    { label: 'pprint-linear', type: 'Function' },
    { label: 'pprint-tabular', type: 'Function' },
    { label: 'pprint-indent', type: 'Function' },
    { label: 'pprint-logical-block', type: 'Macro' },
    { label: 'pprint-newline', type: 'Function' },
    { label: 'pprint-pop', type: 'Local Macro' },
    { label: 'pprint-tab', type: 'Function' },
    { label: 'print-object', type: 'Standard Generic Function' },
    { label: 'print-unreadable-object', type: 'Macro' },
    { label: 'set-pprint-dispatch', type: 'Function' },
    { label: 'write', type: 'Function' },
    { label: 'prin1', type: 'Function' },
    { label: 'print', type: 'Function' },
    { label: 'pprint', type: 'Function' },
    { label: 'princ', type: 'Function' },
    { label: 'write-to-string', type: 'Function' },
    { label: 'prin1-to-string', type: 'Function' },
    { label: 'princ-to-string', type: 'Function' },
    { label: '*print-array*', type: 'Variable' },
    { label: '*print-base*', type: 'Variable' },
    { label: '*print-radix*', type: 'Variable' },
    { label: '*print-case*', type: 'Variable' },
    { label: '*print-circle*', type: 'Variable' },
    { label: '*print-escape*', type: 'Variable' },
    { label: '*print-gensym*', type: 'Variable' },
    { label: '*print-level*', type: 'Variable' },
    { label: '*print-length*', type: 'Variable' },
    { label: '*print-lines*', type: 'Variable' },
    { label: '*print-miser-width*', type: 'Variable' },
    { label: '*print-pprint-dispatch*', type: 'Variable' },
    { label: '*print-pretty*', type: 'Variable' },
    { label: '*print-readably*', type: 'Variable' },
    { label: '*print-right-margin*', type: 'Variable' },
    { label: 'print-not-readable', type: 'Condition Type' },
    { label: 'print-not-readable-object', type: 'Function' },
    { label: 'format', type: 'Function' },
];
