module.exports = [
    { label: 'readtable', type: 'System Class' },
    { label: 'copy-readtable', type: 'Function' },
    { label: 'make-dispatch-macro-character', type: 'Function' },
    { label: 'read', type: 'Function' },
    { label: 'read-preserving-whitespace', type: 'Function' },
    { label: 'read-delimited-list', type: 'Function' },
    { label: 'read-from-string', type: 'Function' },
    { label: 'readtable-case', type: 'Accessor' },
    { label: 'readtablep', type: 'Function' },
    { label: 'set-dispatch-macro-character', type: 'Function' },
    { label: 'get-dispatch-macro-character', type: 'Function' },
    { label: 'set-macro-character', type: 'Function' },
    { label: 'get-macro-character', type: 'Function' },
    { label: 'set-syntax-from-char', type: 'Function' },
    { label: 'with-standard-io-syntax', type: 'Macro' },
    { label: '*read-base*', type: 'Variable' },
    { label: '*read-default-float-format*', type: 'Variable' },
    { label: '*read-eval*', type: 'Variable' },
    { label: '*read-suppress*', type: 'Variable' },
    { label: '*readtable*', type: 'Variable' },
    { label: 'reader-error', type: 'Condition Type' },
];
