module.exports = [
    { label: 'stream', type: 'System Class' },
    { label: 'broadcast-stream', type: 'System Class' },
    { label: 'concatenated-stream', type: 'System Class' },
    { label: 'echo-stream', type: 'System Class' },
    { label: 'file-stream', type: 'System Class' },
    { label: 'string-stream', type: 'System Class' },
    { label: 'synonym-stream', type: 'System Class' },
    { label: 'two-way-stream', type: 'System Class' },
    { label: 'input-stream-p', type: 'Function' },
    { label: 'output-stream-p', type: 'Function' },
    { label: 'interactive-stream-p', type: 'Function' },
    { label: 'open-stream-p', type: 'Function' },
    { label: 'stream-element-type', type: 'Function' },
    { label: 'streamp', type: 'Function' },
    { label: 'read-byte', type: 'Function' },
    { label: 'write-byte', type: 'Function' },
    { label: 'peek-char', type: 'Function' },
    { label: 'read-char', type: 'Function' },
    { label: 'read-char-no-hang', type: 'Function' },
    { label: 'terpri', type: 'Function' },
    { label: 'fresh-line', type: 'Function' },
    { label: 'unread-char', type: 'Function' },
    { label: 'write-char', type: 'Function' },
    { label: 'read-line', type: 'Function' },
    { label: 'write-string', type: 'Function' },
    { label: 'write-line', type: 'Function' },
    { label: 'read-sequence', type: 'Function' },
    { label: 'write-sequence', type: 'Function' },
    { label: 'file-length', type: 'Function' },
    { label: 'file-position', type: 'Function' },
    { label: 'file-string-length', type: 'Function' },
    { label: 'open', type: 'Function' },
    { label: 'stream-external-format', type: 'Function' },
    { label: 'with-open-file', type: 'macro' },
    { label: 'close', type: 'Function' },
    { label: 'with-open-stream', type: 'Macro' },
    { label: 'listen', type: 'Function' },
    { label: 'clear-input', type: 'Function' },
    { label: 'finish-output', type: 'Function' },
    { label: 'force-output', type: 'Function' },
    { label: 'clear-output', type: 'Function' },
    { label: 'y-or-n-p', type: 'Function' },
    { label: 'yes-or-no-p', type: 'Function' },
    { label: 'make-synonym-stream', type: 'Function' },
    { label: 'synonym-stream-symbol', type: 'Function' },
    { label: 'broadcast-stream-streams', type: 'Function' },
    { label: 'make-broadcast-stream', type: 'Function' },
    { label: 'make-two-way-stream', type: 'Function' },
    { label: 'two-way-stream-input-stream', type: 'Function' },
    { label: 'two-way-stream-output-stream', type: 'Function' },
    { label: 'echo-stream-input-stream', type: 'Function' },
    { label: 'echo-stream-output-stream', type: 'Function' },
    { label: 'make-echo-stream', type: 'Function' },
    { label: 'concatenated-stream-streams', type: 'Function' },
    { label: 'make-concatenated-stream', type: 'Function' },
    { label: 'get-output-stream-string', type: 'Function' },
    { label: 'make-string-input-stream', type: 'Function' },
    { label: 'make-string-output-stream', type: 'Function' },
    { label: 'with-input-from-string', type: 'Macro' },
    { label: 'with-output-to-string', type: 'Macro' },
    { label: '*debug-io*', type: 'Variable' },
    { label: '*error-output*', type: 'Variable' },
    { label: '*query-io*', type: 'Variable' },
    { label: '*standard-input*', type: 'Variable' },
    { label: '*standard-output*', type: 'Variable' },
    { label: '*trace-output*', type: 'Variable' },
    { label: '*terminal-io*', type: 'Variable' },
    { label: 'stream-error', type: 'Condition Type' },
    { label: 'stream-error-stream', type: 'Function' },
    { label: 'end-of-file', type: 'Condition Type' },
];
