module.exports = [
    { label: 'boolean', type: 'Type' },
    { label: 'compiled-function', type: 'Type' },
    { label: 'generic-function', type: 'System Class' },
    { label: 'standard-generic-function', type: 'System Class' },
    { label: 'class', type: 'System Class' },
    { label: 'built-in-class', type: 'System Class' },
    { label: 'structure-class', type: 'System Class' },
    { label: 'standard-class', type: 'System Class' },
    { label: 'method', type: 'System Class' },
    { label: 'standard-method', type: 'System Class' },
    { label: 'structure-object', type: 'Class' },
    { label: 'standard-object', type: 'Class' },
    { label: 'method-combination', type: 'System Class' },
    { label: 'satisfies', type: 'Type Specifier' },
    { label: 'coerce', type: 'Function' },
    { label: 'deftype', type: 'Macro' },
    { label: 'subtypep', type: 'Function' },
    { label: 'type-of', type: 'Function' },
    { label: 'typep', type: 'Function' },
    { label: 'type-error', type: 'Condition Type' },
    { label: 'type-error-datum', type: 'Function' },
    { label: 'type-error-expected-type', type: 'Function' },
    { label: 'simple-type-error', type: 'Condition Type' },
];
