module.exports = [
    { label: 'array' },
    { label: 'simple-array' },
    { label: 'vector' },
    { label: 'simple-vector' },
    { label: 'bit-vector' },
    { label: 'simple-bit-vector' },
    {
        label: 'make-array',
        doc: '**(make-array** (dimensions) ***&key*** element-type initial-element initial-contents adjustable fill-pointer displaced-to displaced-index-offset**)**'
    },
    { label: 'adjust-array' },
    { label: 'adjustable-array-p' },
    { label: 'aref' },
    { label: 'array-dimension' },
    { label: 'array-dimensions' },
    { label: 'array-element-type' },
    { label: 'array-has-fill-pointer-p' },
    { label: 'array-displacement' },
    { label: 'array-in-bounds-p' },
    { label: 'array-rank' },
    { label: 'array-row-major-index' },
    { label: 'array-total-size' },
    { label: 'arrayp' },
    { label: 'fill-pointer' },
    { label: 'row-major-aref' },
    { label: 'upgraded-array-element-type' },
    { label: 'array-dimension-limit' },
    { label: 'array-rank-limit' },
    { label: 'array-total-size-limit' },
    { label: 'simple-vector-p' },
    { label: 'svref' },
    { label: 'vector' },
    { label: 'vector-pop' },
    { label: 'vector-push' },
    { label: 'vector-push-extend' },
    { label: 'vectorp' },
    { label: 'bit' },
    { label: 'sbit' },
    { label: 'bit-and' },
    { label: 'bit-andc1' },
    { label: 'bit-andc2' },
    { label: 'bit-eqv' },
    { label: 'bit-ior' },
    { label: 'bit-nand' },
    { label: 'bit-nor' },
    { label: 'bit-not' },
    { label: 'bit-orc1' },
    { label: 'bit-orc2' },
    { label: 'bit-xor' },
    { label: 'bit-vector-p' },
    { label: 'simple-bit-vector-p' },
];
