module.exports = [
    { label: 'pathname' },
    { label: 'logical-pathname' },
    { label: 'pathname' },
    { label: 'make-pathname' },
    { label: 'pathnamep' },
    { label: 'pathname-host' },
    { label: 'pathname-device' },
    { label: 'pathname-directory' },
    { label: 'pathname-name' },
    { label: 'pathname-type' },
    { label: 'pathname-version' },
    { label: 'load-logical-pathname-translations' },
    { label: 'logical-pathname-translations' },
    { label: 'logical-pathname' },
    { label: '*default-pathname-defaults*' },
    { label: 'namestring' },
    { label: 'file-namestring' },
    { label: 'directory-namestring' },
    { label: 'host-namestring' },
    { label: 'enough-namestring' },
    { label: 'parse-namestring' },
    { label: 'wild-pathname-p' },
    { label: 'pathname-match-p' },
    { label: 'translate-logical-pathname' },
    { label: 'translate-pathname' },
    { label: 'merge-pathnames' },
];
