module.exports = [
    { label: 'hash-table' },
    { label: 'make-hash-table' },
    { label: 'hash-table-p' },
    { label: 'hash-table-count' },
    { label: 'hash-table-rehash-size' },
    { label: 'hash-table-rehash-threshold' },
    { label: 'hash-table-size' },
    { label: 'hash-table-test' },
    { label: 'gethash' },
    { label: 'remhash' },
    { label: 'maphash' },
    { label: 'with-hash-table-iterator' },
    { label: 'clrhash' },
    { label: 'sxhash' },
];
