module.exports = [
    { label: 'readtable' },
    { label: 'copy-readtable' },
    { label: 'make-dispatch-macro-character' },
    { label: 'read' },
    { label: 'read-preserving-whitespace' },
    { label: 'read-delimited-list' },
    { label: 'read-from-string' },
    { label: 'readtable-case' },
    { label: 'readtablep' },
    { label: 'set-dispatch-macro-character' },
    { label: 'get-dispatch-macro-character' },
    { label: 'set-macro-character' },
    { label: 'get-macro-character' },
    { label: 'set-syntax-from-char' },
    { label: 'with-standard-io-syntax' },
    { label: '*read-base*' },
    { label: '*read-default-float-format*' },
    { label: '*read-eval*' },
    { label: '*read-suppress*' },
    { label: '*readtable*' },
    { label: 'reader-error' },
];
