module.exports = [
    { label: 'symbol' },
    { label: 'keyword' },
    { label: 'symbolp' },
    { label: 'keywordp' },
    { label: 'make-symbol' },
    { label: 'copy-symbol' },
    { label: 'gensym' },
    { label: '*gensym-counter*' },
    { label: 'gentemp' },
    { label: 'symbol-function' },
    { label: 'symbol-name' },
    { label: 'symbol-package' },
    { label: 'symbol-plist' },
    { label: 'symbol-value' },
    { label: 'get' },
    { label: 'remprop' },
    { label: 'boundp' },
    { label: 'makunbound' },
    { label: 'set' },
    { label: 'unbound-variable' },
];
