module.exports = [
    { label: 'compile-file' },
    { label: 'compile-file-pathname' },
    { label: 'load' },
    { label: 'with-compilation-unit' },
    { label: '*features*' },
    { label: '*compile-file-pathname*' },
    { label: '*compile-file-truename*' },
    { label: '*load-pathname*' },
    { label: '*load-truename*' },
    { label: '*compile-print*' },
    { label: '*compile-verbose*' },
    { label: '*load-print*' },
    { label: '*load-verbose*' },
    { label: '*modules*' },
    { label: 'provide' },
    { label: 'require' },
];
