export default [
    { label: 'character', type: 'System Class' },
    { label: 'base-char', type: 'Type' },
    { label: 'standard-char', type: 'Type' },
    { label: 'extended-char', type: 'Type' },
    { label: 'char=', type: 'Function' },
    { label: 'char/=', type: 'Function' },
    { label: 'char<', type: 'Function' },
    { label: 'char>', type: 'Function' },
    { label: 'char<=', type: 'Function' },
    { label: 'char>=', type: 'Function' },
    { label: 'char-equal', type: 'Function' },
    { label: 'char-not-equal', type: 'Function' },
    { label: 'char-lessp', type: 'Function' },
    { label: 'char-greaterp', type: 'Function' },
    { label: 'char-not-greaterp', type: 'Function' },
    { label: 'char-not-lessp', type: 'Function' },
    { label: 'character', type: 'Function' },
    { label: 'characterp', type: 'Function' },
    { label: 'alpha-char-p', type: 'Function' },
    { label: 'alphanumericp', type: 'Function' },
    { label: 'digit-char', type: 'Function' },
    { label: 'digit-char-p', type: 'Function' },
    { label: 'graphic-char-p', type: 'Function' },
    { label: 'standard-char-p', type: 'Function' },
    { label: 'char-upcase', type: 'Function' },
    { label: 'char-downcase', type: 'Function' },
    { label: 'upper-case-p', type: 'Function' },
    { label: 'lower-case-p', type: 'Function' },
    { label: 'both-case-p', type: 'Function' },
    { label: 'char-code', type: 'Function' },
    { label: 'char-int', type: 'Function' },
    { label: 'code-char', type: 'Function' },
    { label: 'char-code-limit', type: 'Constant Variable' },
    { label: 'char-name', type: 'Function' },
    { label: 'name-char', type: 'Function' },
]
