export default [
    { label: 'hash-table', type: 'System Class' },
    { label: 'make-hash-table', type: 'Function' },
    { label: 'hash-table-p', type: 'Function' },
    { label: 'hash-table-count', type: 'Function' },
    { label: 'hash-table-rehash-size', type: 'Function' },
    { label: 'hash-table-rehash-threshold', type: 'Function' },
    { label: 'hash-table-size', type: 'Function' },
    { label: 'hash-table-test', type: 'Function' },
    { label: 'gethash', type: 'Accessor' },
    { label: 'remhash', type: 'Function' },
    { label: 'maphash', type: 'Function' },
    { label: 'with-hash-table-iterator', type: 'Macro' },
    { label: 'clrhash', type: 'Function' },
    { label: 'sxhash', type: 'Function' },
]
