export default [
    { label: 'symbol', type: 'System Class' },
    { label: 'keyword', type: 'Type' },
    { label: 'symbolp', type: 'Function' },
    { label: 'keywordp', type: 'Function' },
    { label: 'make-symbol', type: 'Function' },
    { label: 'copy-symbol', type: 'Function' },
    { label: 'gensym', type: 'Function' },
    { label: '*gensym-counter*', type: 'Variable' },
    { label: 'gentemp', type: 'Function' },
    { label: 'symbol-function', type: 'Accessor' },
    { label: 'symbol-name', type: 'Function' },
    { label: 'symbol-package', type: 'Function' },
    { label: 'symbol-plist', type: 'Accessor' },
    { label: 'symbol-value', type: 'Accessor' },
    { label: 'get', type: 'Accessor' },
    { label: 'remprop', type: 'Function' },
    { label: 'boundp', type: 'Function' },
    { label: 'makunbound', type: 'Function' },
    { label: 'set', type: 'Function' },
    { label: 'unbound-variable', type: 'Condition Type' },
];
