export default [
    { label: 'compile-file', type: 'Function' },
    { label: 'compile-file-pathname', type: 'Function' },
    { label: 'load', type: 'Function' },
    { label: 'with-compilation-unit', type: 'Macro' },
    { label: '*features*', type: 'Variable' },
    { label: '*compile-file-pathname*', type: 'Variable' },
    { label: '*compile-file-truename*', type: 'Variable' },
    { label: '*load-pathname*', type: 'Variable' },
    { label: '*load-truename*', type: 'Variable' },
    { label: '*compile-print*', type: 'Variable' },
    { label: '*compile-verbose*', type: 'Variable' },
    { label: '*load-print*', type: 'Variable' },
    { label: '*load-verbose*', type: 'Variable' },
    { label: '*modules*', type: 'Variable' },
    { label: 'provide', type: 'Function' },
    { label: 'require', type: 'Function' },
]
